# get all items
GET http://localhost:3000/item

###
# get item by id
GET http://localhost:3000/item/id/637a7c1cb4b3daa67e692f99

###
# create item
POST  http://localhost:3000/item/create
Content-Type: application/json

{
    "name": "paprika",
    "amount": 10,
    "unit": "dkg"
}

###
# delete item
DELETE  http://localhost:3000/item/delete/id/637a9120751f6620c8d2b8de