###
# login user
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "name": "John",
    "password": "1234"
}

###
# get all (admin)
GET http://localhost:3000/shoppingList
sessionId: hf6kCxlQ1e

###
#  get all my
GET http://localhost:3000/shoppingList/owned
sessionId: kjSOwBUxNa

###
#  get all not my
GET http://localhost:3000/shoppingList/notowned
sessionId: kjSOwBUxNa

###
#  get one my
GET http://localhost:3000/shoppingList/shoppingListId/639f00230a5394b45e3bc0ba
sessionId: kjSOwBUxNa

###
# create shopping list
POST  http://localhost:3000/shoppingList/create
sessionId: J53WvTvRom
Content-Type: application/json

{
    "name": "Testovaci nakupni listek"
}

###
# delete shopping list
DELETE  http://localhost:3000/shoppingList/shoppingListId/639efa0034f2db425f8f51a2
sessionId: kjSOwBUxNa

###
# add item to shopping list
PATCH http://localhost:3000/shoppingList/addItem
sessionId: kjSOwBUxNa
Content-Type: application/json

{
    "shoppingListId": "639f00230a5394b45e3bc0ba",
    "name": "jahody",
    "quantity": 5
}

###
# remove item from shopping list
PATCH http://localhost:3000/shoppingList/removeItem
sessionId: kjSOwBUxNa
Content-Type: application/json

{
    "shoppingListId": "639f00230a5394b45e3bc0ba",
    "itemId": "639f04c5ad32c3db76975e66"
}

###
# add user to shopping list
PATCH http://localhost:3000/shoppingList/addUser
sessionId: kjSOwBUxNa
Content-Type: application/json

{
    "shoppingListId": "639f00230a5394b45e3bc0ba",
    "userId": "639ee49e1fed8a3a8faa5195"
}

###
# remove user from shopping list
PATCH http://localhost:3000/shoppingList/removeUser
sessionId: kjSOwBUxNa
Content-Type: application/json

{
    "shoppingListId": "639f00230a5394b45e3bc0ba",
    "userId": "639ee49e1fed8a3a8faa5195"
}