# get all users
GET http://localhost:3000/user
sessionId: eCQNYfOCNK

###
# get user by id
GET http://localhost:3000/user/id/637a82aeee981dfe4596588e

###
# create user
POST  http://localhost:3000/user/create
Content-Type: application/json

{
    "name": "jjj",
    "password": "1234"
}

###
# delete user
DELETE  http://localhost:3000/user/id/639f16bd5e56ebf45d7d1185
sessionId: eCQNYfOCNK

###
# login user
POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "name": "John",
    "password": "1234"
}

###
# logout user
POST http://localhost:3000/user/logout
sessionId: S0da2gO4j4

###
# update user role
PUT  http://localhost:3000/user/role/admin/id/639ee8b29244369736621946
sessionId: z2kzw73HxR